# Generated by Django 4.2.7 on 2023-11-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='first_places',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
